server:
  port: ${PORT:8083}
spring:
  application:
    name: api-catalog
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672  
  zipkin:
    baseUrl: http://localhost:9411/
  data:
    mongodb:
      username: usr-inscription-mongo
      password: pwd-inscription-mongo
      database: catalog
      port: 27025
      host: localhost
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

info:
  application:
    name: api-catalog

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
